apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: hello-go
spec:
  image: registry.digitalocean.com/enigmacamp/simple-go
  interval: 1m
  secretRef:
    name: regcred

---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: hello-java
spec:
  image: registry.digitalocean.com/enigmacamp/simple-java
  interval: 1m
  secretRef:
    name: regcred